name: 'S3 Website PR'
description: 'Automatically deploy built PR bundles to an S3 static website.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  bucket-name:
    description: 'Name of the S3 bucket used to store bundles.'
    required: true
  folder-to-copy:
    description: 'Folder to copy assets from into S3.'
    required: false
  environment-prefix:
    description: 'Prefix of the GitHub Deployment Environment. The PR number will be appended to this value.'
    required: false
  website-url-template:
    description: 'A template to create a custom website url instead of the bucket name'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
